//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Currency { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
